blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/lathoub/Arduino-AppleMIDI-Library/discussions
    about: Not a bug or a feature request ? Discuss your problem, ask for help or show what you've built in Discussions.
